### ISSUE TITLE
GoogleLocationFetcher

### ISSUE THREAD

**Issue by lamaj411** [Shashank2406/react-native-google-location-fetcher#2]
Hi,
result= GoogleLocationFetcher.getLocationName(latitude,longitude)
unable to access result.address.address

**Comment by Shashank2406** [comment]
can you console and check the result variable?

**Comment by lamaj411** [comment]
i got the result.address,but result.address.address is undefined

**Comment by Shashank2406** [comment]
why do you need result.address.address?

**Comment by lamaj411** [comment]
to display the location address

**Comment by lamaj411** [comment]
i got the response like the following.I couldnt get address value by using "result.address.address"
result={ address:{
address: "Addres value"
description: "Location Name Fetched Successfully"}}

**Comment by Shashank2406** [comment]
this is not a package issue, please check if you are accessing it properly
